# Generated by Django 3.2.7 on 2021-10-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0002_auto_20211028_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='inventario',
            field=models.IntegerField(verbose_name='inventario'),
        ),
    ]
