from .UserCreateView import UserCreateView
from .UserDetailView import UserDetailView
from .UserUpdateView import UserUpdateView
from .UserDeleteView import UserDeleteView
from .UserListView import UserListView
from .ProductoCreateView import ProductoCreateView
from .ProductoDetailView import ProductoDetailView
from .ProductoDeleteView import ProductoDeleteView
from .ProductoUpdateView import ProductoUpdateView
from .ProductoListView import ProductoListView
from .InventarioCreateView import InventarioCreateView
from .InventarioDetailView import InventarioDetailView
from .InventarioDeleteView import InventarioDeleteView
from .InventarioUpdateView import InventarioUpdateView
from .InventarioListView import InventarioListView
from .ProveedorCreateView import ProveedorCreateView
from .ProveedorDetailView import ProveedorDetailView
from .ProveedorUpdateView import ProveedorUpdateView
from .ProveedorListView import ProveedorListView
from .ProveedorDeleteView import ProveedorDeleteView
from .CompraCreateView import CompraCreateView
